{{ config(
    materialized='table'
) }}

WITH parsed_json AS (
    SELECT
        (_airbyte_data->>'hr')::INT AS hr,
        (_airbyte_data->>'__v')::INT AS version,
        (_airbyte_data->'_id'->>'$oid')::TEXT AS id,
        (_airbyte_data->>'age')::INT AS age,
        (_airbyte_data->>'bmi')::FLOAT AS bmi,
        (_airbyte_data->>'bmr')::FLOAT AS bmr,
        (_airbyte_data->>'smi')::FLOAT AS smi,
        (_airbyte_data->'time'->>'$numberLong')::BIGINT AS time,
        (_airbyte_data->>'state')::INT AS state,
        (_airbyte_data->>'bfmMax')::FLOAT AS bfm_max,
        (_airbyte_data->>'bfmMin')::FLOAT AS bfm_min,
        (_airbyte_data->>'bfpMax')::FLOAT AS bfp_max,
        (_airbyte_data->>'bfpMin')::FLOAT AS bfp_min,
        (_airbyte_data->>'bmiMax')::FLOAT AS bmi_max,
        (_airbyte_data->>'bmiMin')::FLOAT AS bmi_min,
        (_airbyte_data->>'bmrMax')::FLOAT AS bmr_max,
        (_airbyte_data->>'bmrMin')::FLOAT AS bmr_min,
        (_airbyte_data->>'height')::INT AS height,
        (_airbyte_data->>'smmMax')::FLOAT AS smm_max,
        (_airbyte_data->>'smmMin')::FLOAT AS smm_min,
        (_airbyte_data->>'allBody')::FLOAT AS all_body,
        (_airbyte_data->>'boneMax')::FLOAT AS bone_max,
        (_airbyte_data->>'boneMin')::FLOAT AS bone_min,
        (_airbyte_data->>'handled')::BOOLEAN AS handled,
        (_airbyte_data->>'leftArm')::FLOAT AS left_arm,
        (_airbyte_data->>'leftLeg')::FLOAT AS left_leg,
        (_airbyte_data->>'bodyType')::INT AS body_type,
        (_airbyte_data->>'boneMass')::FLOAT AS bone_mass,
        (_airbyte_data->>'muscleKg')::FLOAT AS muscle_kg,
        (_airbyte_data->>'nickName')::TEXT AS nickname,
        (_airbyte_data->>'owner_id')::TEXT AS owner_id,
        (_airbyte_data->>'rightArm')::FLOAT AS right_arm,
        (_airbyte_data->>'rightLeg')::FLOAT AS right_leg,
        (_airbyte_data->>'timezone')::TEXT AS timezone,
        (_airbyte_data->>'weightkg')::FLOAT AS weight_kg,
        (_airbyte_data->>'weightlb')::FLOAT AS weight_lb,
        (_airbyte_data->>'weightst')::FLOAT AS weight_st,
        (_airbyte_data->>'allBodykg')::FLOAT AS all_body_kg,
        (_airbyte_data->>'bodyScore')::INT AS body_score,
        (_airbyte_data->'createdAt'->>'$date')::TIMESTAMP AS created_at,
        (_airbyte_data->'deletedAt'->>'$date')::TIMESTAMP AS deleted_at,
        (_airbyte_data->>'electrode')::INT AS electrode,
        (_airbyte_data->>'leftArmkg')::FLOAT AS left_arm_kg,
        (_airbyte_data->>'leftLegkg')::FLOAT AS left_leg_kg,
        (_airbyte_data->>'proteinKg')::FLOAT AS protein_kg,
        (_airbyte_data->>'smPercent')::FLOAT AS sm_percent,
        (_airbyte_data->>'weightMax')::FLOAT AS weight_max,
        (_airbyte_data->>'weightMin')::FLOAT AS weight_min,
        (_airbyte_data->>'bfmControl')::FLOAT AS bfm_control,
        (_airbyte_data->>'ffmControl')::FLOAT AS ffm_control,
        (_airbyte_data->>'rightArmkg')::FLOAT AS right_arm_kg,
        (_airbyte_data->>'rightLegkg')::FLOAT AS right_leg_kg,
        (_airbyte_data->>'bfmStandard')::FLOAT AS bfm_standard,
        (_airbyte_data->>'bfpStandard')::FLOAT AS bfp_standard,
        (_airbyte_data->>'bmiStandard')::FLOAT AS bmi_standard,
        (_airbyte_data->>'bmrStandard')::FLOAT AS bmr_standard,
        (_airbyte_data->>'bodyWaterKg')::FLOAT AS body_water_kg,
        (_airbyte_data->>'ffmStandard')::FLOAT AS ffm_standard,
        (_airbyte_data->>'isSupportHR')::BOOLEAN AS is_support_hr,
        (_airbyte_data->>'physicalAge')::INT AS physical_age,
        (_airbyte_data->>'precisionKg')::INT AS precision_kg,
        (_airbyte_data->>'precisionLb')::INT AS precision_lb,
        (_airbyte_data->>'smmStandard')::FLOAT AS smm_standard,
        (_airbyte_data->>'temperature')::FLOAT AS temperature,
        (_airbyte_data->>'visceralFat')::INT AS visceral_fat,
        (_airbyte_data->>'weightGrama')::INT AS weight_grama,
        (_airbyte_data->>'targetWeight')::FLOAT AS target_weight,
        (_airbyte_data->>'waterMassMax')::FLOAT AS water_mass_max,
        (_airbyte_data->>'waterMassMin')::FLOAT AS water_mass_min,
        (_airbyte_data->>'allBodyMuscle')::FLOAT AS all_body_muscle,
        (_airbyte_data->>'biologicalSex')::TEXT AS biological_sex,
        (_airbyte_data->>'bmiEvaluation')::TEXT AS bmi_evaluation,
        (_airbyte_data->>'bodyFatMassKg')::FLOAT AS body_fat_mass_kg,
        (_airbyte_data->>'leftArmmuscle')::FLOAT AS left_arm_muscle,
        (_airbyte_data->>'leftLegMuscle')::FLOAT AS left_leg_muscle,
        (_airbyte_data->>'muscleMassMax')::FLOAT AS muscle_mass_max,
        (_airbyte_data->>'muscleMassMin')::FLOAT AS muscle_mass_min,
        (_airbyte_data->>'musclePercent')::FLOAT AS muscle_percent,
        (_airbyte_data->>'obesityDegree')::INT AS obesity_degree,
        (_airbyte_data->>'precisionStlb')::INT AS precision_stlb,
        (_airbyte_data->>'weightControl')::FLOAT AS weight_control,
        (_airbyte_data->>'bodyFatPercent')::FLOAT AS body_fat_percent,
        (_airbyte_data->>'proteinMassMax')::FLOAT AS protein_mass_max,
        (_airbyte_data->>'proteinMassMin')::FLOAT AS protein_mass_min,
        (_airbyte_data->>'proteinPercent')::FLOAT AS protein_percent,
        (_airbyte_data->>'rightArmMuscle')::FLOAT AS right_arm_muscle,
        (_airbyte_data->>'rightLegMuscle')::FLOAT AS right_leg_muscle,
        (_airbyte_data->>'weightStandard')::FLOAT AS weight_standard,
        (_airbyte_data->>'allBodyMusclekg')::FLOAT AS all_body_muscle_kg,
        (_airbyte_data->>'kgScaleDivision')::INT AS kg_scale_division,
        (_airbyte_data->>'lbScaleDivision')::INT AS lb_scale_division,
        (_airbyte_data->>'leftArmMusclekg')::FLOAT AS left_arm_muscle_kg,
        (_airbyte_data->>'leftLegMusclekg')::FLOAT AS left_leg_muscle_kg,
        (_airbyte_data->>'moisturePercent')::FLOAT AS moisture_percent,
        (_airbyte_data->>'rightArmMusclekg')::FLOAT AS right_arm_muscle_kg,
        (_airbyte_data->>'rightLegMusclekg')::FLOAT AS right_leg_muscle_kg,
        (_airbyte_data->>'skeletalMuscleKg')::FLOAT AS skeletal_muscle_kg,
        (_airbyte_data->>'bodyScoreEvaluation')::TEXT AS body_score_evaluation,
        (_airbyte_data->>'subcutaneousFatPercent')::FLOAT AS subcutaneous_fat_percent,
        (_airbyte_data->>'muscleFatLeftArmEvaluation')::TEXT AS muscle_fat_left_arm_evaluation,
        (_airbyte_data->>'muscleFatLeftLegEvaluation')::TEXT AS muscle_fat_left_leg_evaluation,
        (_airbyte_data->>'muscleFatRightArmEvaluation')::TEXT AS muscle_fat_right_arm_evaluation,
        (_airbyte_data->>'muscleFatRightLegEvaluation')::TEXT AS muscle_fat_right_leg_evaluation,
        (_airbyte_data->>'muscleBalanceLeftArmEvaluation')::TEXT AS muscle_balance_left_arm_evaluation,
        (_airbyte_data->>'muscleBalanceLeftLegEvaluation')::TEXT AS muscle_balance_left_leg_evaluation,
        (_airbyte_data->>'muscleBalanceRightArmEvaluation')::TEXT AS muscle_balance_right_arm_evaluation,
        (_airbyte_data->>'muscleBalanceRightLegEvaluation')::TEXT AS muscle_balance_right_leg_evaluation
    FROM
        {{ source('bronze', 'airbyte_raw_weighins') }}
)

SELECT * FROM parsed_json
