version: 2

sources:
  - name: bronze  # Replace with your actual database name
    schema: public  # Replace with your schema if different
    tables:
      - name: airbyte_raw_weighins
      
      - name: customer

      - name: customer_meal_plan

      - name: customer_medicines_prescriptions

      - name: customer_objectives

      - name: meal_plans

      - name: medicines

      - name: objectives
