version: 2

sources:
  - name: bronze  
    schema: bronze
    tables:
      - name: airbyte_raw_weighins
      
      - name: customer

      - name: customer_meal_plan

      - name: customer_medicines_prescriptions

      - name: customer_objectives

      - name: meal_plans

      - name: medicines

      - name: objectives

